name: diffae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
- python=3.6.15
- pytorch=1.7.1
- torchvision=0.8.2
- cudatoolkit=11.0
- pytorch-lightning=1.4.5
- torchmetrics=0.5.0
- pip=21.0.1
- pip:
    - scipy==1.5.4
    - numpy==1.19.5
    - tqdm
    - pytorch-fid==0.2.0
    - pandas==1.1.5
    - lpips==0.1.4
    - lmdb==1.2.1
    - ftfy
    - regex
    - notebook==6.4.4
    - matplotlib==3.3.4

